# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    dev.triplethreats.ekwalsharez: INFO

spring:
  profiles:
    active: prod
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: ekwalshare
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: prod
    change-log: classpath:config/liquibase/master.xml

server:
  port: 3000